import { ArticleInfo } from "./article-info";

export const BlogPageArticlesDir = "assets/blog-page-articles/";

export const BlogPageArticles = [
  new ArticleInfo(
    /* File path   */ "test copy 10.md",
    /* Title       */ "Test Copy",
    /* Description */ "Description description description description",
    /* Date        */ "April 5 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 11.md",
    /* Title       */ "Test Copy 11",
    /* Description */ "Description description description description",
    /* Date        */ "March 20 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 12.md",
    /* Title       */ "Test Copy 12",
    /* Description */ "Description description description description",
    /* Date        */ "March 10 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 13.md",
    /* Title       */ "Test Copy 13",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 14.md",
    /* Title       */ "Test Copy 14",
    /* Description */ "Description description description description",
    /* Date        */ "July 14 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 2.md",
    /* Title       */ "Test Copy 2",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 3.md",
    /* Title       */ "Test Copy 3",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 4.md",
    /* Title       */ "Test Copy 4",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 5.md",
    /* Title       */ "Test Copy 5",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 6.md",
    /* Title       */ "Test Copy 6",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 7.md",
    /* Title       */ "Test Copy 7",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 8.md",
    /* Title       */ "Test Copy 8",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy 9.md",
    /* Title       */ "Test Copy 9",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test copy.md",
    /* Title       */ "Test Copy",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test.md",
    /* Title       */ "Test",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
  new ArticleInfo(
    /* File path   */ "test_two.md",
    /* Title       */ "Test Two",
    /* Description */ "Description description description description",
    /* Date        */ "March 4 2022",
    /* Image Path  */ "assets/images/wide-club.png",
    /* Authors     */ [],
    /* Tags        */ ["Joe", "Mama", "Tag one", "Tag 2"],
  ),
]